language: php

php:
- '7.2'
- '7.1'
- '7.0'
- '5.6'


sudo: false


before_script:
- composer self-update
- composer --version
- THEME_SLUG=$(pwd)
- cd ~
- git clone https://github.com/squizlabs/PHP_CodeSniffer.git phpcs
- git clone https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git wpcs
- ~/phpcs/bin/phpcs --config-set installed_paths ~/wpcs
- cd "$THEME_SLUG"
- phpenv rehash

script:

- ~/phpcs/bin/phpcs -p -s -v -n --standard=ruleset.xml --extensions=php .

notifications:
  slack: jonathansblog:xcTlLtSp7QrTmEjxjH9Jq3bR
  email: false
